<?php

declare(strict_types=1);

namespace App\Shared\Infrastructure\Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * refresh_token.id → IDENTITY (апгрейд DBAL 3→4 / ORM 3.7).
 *
 * strategy=AUTO на PostgreSQL раньше (DBAL 3 / ORM ≤3.1) эмулировалась через отдельную SEQUENCE:
 * колонка была INT NOT NULL без DEFAULT, а ORM сам звал nextval('refresh_token_id_seq') и включал id в INSERT.
 * В DBAL 4 / ORM 3.7 AUTO резолвится в native IDENTITY: ORM опускает id из INSERT и ждёт, что колонка
 * сгенерирует его сама. Со старой схемой это даёт "null value in column id". Конвертируем колонку в
 * IDENTITY и убираем ненужную теперь standalone-sequence. Идемпотентно (guard по is_identity).
 */
final class Version20260924120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'refresh_token.id → GENERATED BY DEFAULT AS IDENTITY (DBAL4/ORM3.7 AUTO=IDENTITY).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'refresh_token' AND column_name = 'id' AND is_identity = 'YES'
                ) THEN
                    ALTER TABLE refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                    PERFORM setval(
                        pg_get_serial_sequence('refresh_token', 'id'),
                        COALESCE((SELECT MAX(id) FROM refresh_token), 0) + 1,
                        false
                    );
                END IF;
            END $$;
        SQL);
        $this->addSql('DROP SEQUENCE IF EXISTS refresh_token_id_seq CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE SEQUENCE IF NOT EXISTS refresh_token_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('ALTER TABLE refresh_token ALTER COLUMN id DROP IDENTITY IF EXISTS');
    }
}
