<?php

declare(strict_types=1);

namespace App\Shared\Infrastructure\Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Append-only журнал; триггер блокирует UPDATE/DELETE (Уровень 1). Идемпотентно. */
final class Version20260916120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create append-only audit_log with UPDATE/DELETE-blocking trigger.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS audit_log (
                id UUID NOT NULL,
                seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
                entity_class VARCHAR(255) NOT NULL,
                entity_id VARCHAR(64) NOT NULL,
                action VARCHAR(16) NOT NULL,
                changes JSONB NOT NULL,
                actor_id VARCHAR(64) NOT NULL,
                occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log (entity_class, entity_id, seq)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_audit_class ON audit_log (entity_class, occurred_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log (actor_id, occurred_at)');
        $this->addSql("COMMENT ON COLUMN audit_log.id IS '(DC2Type:uuid)'");
        $this->addSql("COMMENT ON COLUMN audit_log.occurred_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql(<<<'SQL'
            CREATE OR REPLACE FUNCTION audit_log_block_mutation() RETURNS trigger AS $$
            BEGIN RAISE EXCEPTION 'audit_log is append-only'; END; $$ LANGUAGE plpgsql
        SQL);
        $this->addSql('DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log');
        $this->addSql(<<<'SQL'
            CREATE TRIGGER audit_log_no_update_delete BEFORE UPDATE OR DELETE ON audit_log
                FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation()
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log');
        $this->addSql('DROP FUNCTION IF EXISTS audit_log_block_mutation()');
        $this->addSql('DROP TABLE IF EXISTS audit_log');
    }
}
