monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - coating
    handlers:
        error:
            type: fingers_crossed
            # 500 errors are logged at the critical level
            action_level: error
            # to also log 400 level errors (but not 404's):
            # action_level: error
            excluded_http_codes: [ 401, 403, 404 ]
            channels: [ "!event", "!security", "!doctrine", "!deprecation", "!console" ]
#            channels: [ "!deprecation" ]
            handler: deduplicated
        deduplicated:
            type: deduplication
            # the time in seconds during which duplicate entries are discarded (default: 60)
            time: 10
            handler: telegram
        telegram: # Важна только эта часть
            type: service
            id: telegram_handler
            channels:
             -  coating
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: [ "!event", "!doctrine", "!console" ]

#when@dev:
#    monolog:
#        handlers:
#            main:
#                type: stream
#                path: "%kernel.logs_dir%/%kernel.environment%.log"
#                level: debug
#                channels: ["!event"]
#            # uncomment to get logging in your browser
#            # you may have to allow bigger header sizes in your Web server configuration
#            #firephp:
#            #    type: firephp
#            #    level: info
#            #chromephp:
#            #    type: chromephp
#            #    level: info
#            console:
#                type: console
#                process_psr_3_messages: false
#                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
